/**
 * RBAC Permission Matrix
 *
 * Maps each UserRole to the exact set of Permissions it holds.
 * Server-side source of truth for authorization decisions.
 */

import { UserRole, Permission, USER_ROLES, PERMISSIONS } from "../constants";

type PermissionMatrix = Record<UserRole, ReadonlyArray<Permission>>;

const ALL_PERMISSIONS: ReadonlyArray<Permission> = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: PermissionMatrix = {
  [USER_ROLES.PLATFORM_ADMIN]: ALL_PERMISSIONS,
  [USER_ROLES.SUPER_ADMIN]: ALL_PERMISSIONS, // Legacy alias

  [USER_ROLES.TENANT_OWNER]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.MODULE_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_FEATURE_CREATE,
    PERMISSIONS.GIS_FEATURE_UPDATE,
    PERMISSIONS.GIS_FEATURE_DELETE,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_CREATE,
    PERMISSIONS.GEOFENCE_UPDATE,
    PERMISSIONS.GEOFENCE_DELETE,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GEOFENCE_MANAGE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_QUERY_ADVANCED,
    PERMISSIONS.GIS_ANALYTICS_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    PERMISSIONS.GIS_EVENTS_ANALYTICS,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_CREATE,
    PERMISSIONS.GIS_RULES_UPDATE,
    PERMISSIONS.GIS_RULES_ACTIVATE,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_RULES_DELETE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_CREATE,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_INVITE,
    PERMISSIONS.ORGANIZATION_MEMBERS_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_REMOVE,
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_ARCHIVE,
    // Phase 13
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.PLAN_MANAGE,
    PERMISSIONS.ENTITLEMENT_READ,
    PERMISSIONS.USAGE_READ,
    PERMISSIONS.OVERRIDE_MANAGE,
  ],

  [USER_ROLES.TENANT_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_FEATURE_CREATE,
    PERMISSIONS.GIS_FEATURE_UPDATE,
    PERMISSIONS.GIS_FEATURE_DELETE,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_CREATE,
    PERMISSIONS.GEOFENCE_UPDATE,
    PERMISSIONS.GEOFENCE_DELETE,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GEOFENCE_MANAGE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_QUERY_ADVANCED,
    PERMISSIONS.GIS_ANALYTICS_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    PERMISSIONS.GIS_EVENTS_ANALYTICS,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_CREATE,
    PERMISSIONS.GIS_RULES_UPDATE,
    PERMISSIONS.GIS_RULES_ACTIVATE,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_RULES_DELETE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_CREATE,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_INVITE,
    PERMISSIONS.ORGANIZATION_MEMBERS_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_REMOVE,
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_ARCHIVE,
    // Phase 13
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.ENTITLEMENT_READ,
    PERMISSIONS.USAGE_READ,
  ],

  [USER_ROLES.ORG_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_FEATURE_CREATE,
    PERMISSIONS.GIS_FEATURE_UPDATE,
    PERMISSIONS.GIS_FEATURE_DELETE,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_CREATE,
    PERMISSIONS.GEOFENCE_UPDATE,
    PERMISSIONS.GEOFENCE_DELETE,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GEOFENCE_MANAGE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_QUERY_ADVANCED,
    PERMISSIONS.GIS_ANALYTICS_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    PERMISSIONS.GIS_EVENTS_ANALYTICS,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_CREATE,
    PERMISSIONS.GIS_RULES_UPDATE,
    PERMISSIONS.GIS_RULES_ACTIVATE,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_RULES_DELETE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_CREATE,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_INVITE,
    PERMISSIONS.ORGANIZATION_MEMBERS_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_REMOVE,
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_ARCHIVE,
    // Phase 13
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.ENTITLEMENT_READ,
    PERMISSIONS.USAGE_READ,
  ],

  [USER_ROLES.MANAGER]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_FEATURE_CREATE,
    PERMISSIONS.GIS_FEATURE_UPDATE,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_CREATE,
    PERMISSIONS.GEOFENCE_UPDATE,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GEOFENCE_MANAGE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    PERMISSIONS.REPORTS_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_QUERY_ADVANCED,
    PERMISSIONS.GIS_ANALYTICS_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    PERMISSIONS.GIS_EVENTS_ANALYTICS,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_CREATE,
    PERMISSIONS.GIS_RULES_UPDATE,
    PERMISSIONS.GIS_RULES_ACTIVATE,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_CREATE,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.WORKSPACE_UPDATE,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
    PERMISSIONS.PLAN_READ,
  ],

  [USER_ROLES.OPERATOR]: [
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    PERMISSIONS.GIS_EVENTS_ANALYTICS,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WORKSPACE_READ,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
  ],

  [USER_ROLES.DISPATCHER]: [
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.ROUTING_CALCULATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_RULES_EXECUTE,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_ALERTS_UPDATE,
    PERMISSIONS.GIS_TASKS_READ,
    PERMISSIONS.GIS_TASKS_UPDATE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WORKSPACE_READ,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
  ],

  [USER_ROLES.FIELD_AGENT]: [
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_FEATURE_UPDATE,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.GIS_SPATIAL_OPERATE,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_EVALUATE,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WORKSPACE_READ,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
  ],

  [USER_ROLES.DRIVER]: [
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRACKING_UPDATE_OWN,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GIS_LOCATION_INGEST,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WORKSPACE_READ,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
  ],

  [USER_ROLES.VIEWER]: [
    PERMISSIONS.GIS_MAP_READ,
    PERMISSIONS.GIS_FEATURE_READ,
    PERMISSIONS.GIS_SPATIAL_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRACKING_READ_LIVE,
    PERMISSIONS.TRACKING_READ_HISTORY,
    PERMISSIONS.TRACKING_LOCATION_READ,
    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GIS_LOCATION_READ,
    PERMISSIONS.GIS_LOCATION_HISTORY,
    PERMISSIONS.GIS_REALTIME_SUBSCRIBE,
    PERMISSIONS.GIS_EVENT_READ,
    // Phase 10
    PERMISSIONS.GIS_QUERY_READ,
    PERMISSIONS.GIS_HISTORY_READ,
    // Phase 11
    PERMISSIONS.GIS_RULES_READ,
    PERMISSIONS.GIS_ALERTS_READ,
    PERMISSIONS.GIS_TASKS_READ,
    // Phase 12
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WORKSPACE_READ,
    // Phase 13
    PERMISSIONS.ENTITLEMENT_READ,
    PERMISSIONS.PLAN_READ,
  ],
};

/**
 * Check if a role has a specific permission.
 */
export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/**
 * Get all permissions for a given role.
 */
export function getPermissionsForRole(
  role: UserRole,
): ReadonlyArray<Permission> {
  return ROLE_PERMISSIONS[role] ?? [];
}

/**
 * Check if a role has ALL of the given permissions.
 */
export function hasAllPermissions(
  role: UserRole,
  permissions: Permission[],
): boolean {
  return permissions.every((p) => hasPermission(role, p));
}

/**
 * Check if a role has ANY of the given permissions.
 */
export function hasAnyPermission(
  role: UserRole,
  permissions: Permission[],
): boolean {
  return permissions.some((p) => hasPermission(role, p));
}
